#ifndef FFT_ABILITY_FLAGS_H
#define FFT_ABILITY_FLAGS_H

/* Learned support and movement abilities are stored as MSB-first bitsets in
 * battle_stats_t. The same four support bytes are copied to party_data_t at
 * 0x124, so these values are shared by MAIN, BATTLE, and WORLD. */
typedef enum battle_support_set_1 {
    BATTLE_SUPPORT_SET_1_EQUIP_ARMOR = 0x80,
    BATTLE_SUPPORT_SET_1_EQUIP_SHIELD = 0x40,
    BATTLE_SUPPORT_SET_1_EQUIP_SWORD = 0x20,
    BATTLE_SUPPORT_SET_1_EQUIP_KATANA = 0x10,
    BATTLE_SUPPORT_SET_1_EQUIP_CROSSBOW = 0x08,
    BATTLE_SUPPORT_SET_1_EQUIP_SPEAR = 0x04,
    BATTLE_SUPPORT_SET_1_EQUIP_AXE = 0x02,
    BATTLE_SUPPORT_SET_1_EQUIP_GUN = 0x01,
} battle_unit_support_set_1_e;

typedef enum battle_support_set_2 {
    BATTLE_SUPPORT_SET_2_HALF_MP = 0x80,
    BATTLE_SUPPORT_SET_2_GAINED_JP_UP = 0x40,
    BATTLE_SUPPORT_SET_2_GAINED_EXP_UP = 0x20,
    BATTLE_SUPPORT_SET_2_ATTACK_UP = 0x10,
    BATTLE_SUPPORT_SET_2_DEFENSE_UP = 0x08,
    BATTLE_SUPPORT_SET_2_MAGIC_ATTACK_UP = 0x04,
    BATTLE_SUPPORT_SET_2_MAGIC_DEFENSE_UP = 0x02,
    BATTLE_SUPPORT_SET_2_CONCENTRATE = 0x01,
} battle_unit_support_set_2_e;

typedef enum battle_support_set_3 {
    BATTLE_SUPPORT_SET_3_TRAIN = 0x80,
    BATTLE_SUPPORT_SET_3_SECRET_HUNT = 0x40,
    BATTLE_SUPPORT_SET_3_MARTIAL_ARTS = 0x20,
    BATTLE_SUPPORT_SET_3_MONSTER_TALK = 0x10,
    BATTLE_SUPPORT_SET_3_THROW_ITEM = 0x08,
    BATTLE_SUPPORT_SET_3_MAINTENANCE = 0x04,
    BATTLE_SUPPORT_SET_3_TWO_HANDS = 0x02,
    BATTLE_SUPPORT_SET_3_TWO_SWORDS = 0x01,
} battle_unit_support_set_3_e;

typedef enum battle_support_set_4 {
    BATTLE_SUPPORT_SET_4_MONSTER_SKILL = 0x80,
    BATTLE_SUPPORT_SET_4_DEFEND = 0x40,
    BATTLE_SUPPORT_SET_4_EQUIP_CHANGE = 0x20,
    BATTLE_SUPPORT_SET_4_SHORT_CHARGE = 0x08,
    BATTLE_SUPPORT_SET_4_NON_CHARGE = 0x04,
} battle_unit_support_set_4_e;

/* Active reaction abilities occupy four MSB-first bytes at
 * battle_stats_t + 0x08b. These values are verified against the target's
 * reaction dispatchers. */
typedef enum battle_unit_reaction_set_1 {
    BATTLE_REACTION_SET_1_PA_SAVE = 0x80,
    BATTLE_REACTION_SET_1_MA_SAVE = 0x40,
    BATTLE_REACTION_SET_1_SPEED_SAVE = 0x20,
    BATTLE_REACTION_SET_1_SUNKEN_STATE = 0x10,
    BATTLE_REACTION_SET_1_CAUTION = 0x08,
    BATTLE_REACTION_SET_1_DRAGON_SPIRIT = 0x04,
    BATTLE_REACTION_SET_1_REGENERATOR = 0x02,
    BATTLE_REACTION_SET_1_BRAVE_UP = 0x01,
} battle_unit_reaction_set_1_e;

typedef enum battle_unit_reaction_set_2 {
    BATTLE_REACTION_SET_2_FAITH_UP = 0x80,
    BATTLE_REACTION_SET_2_HP_RESTORE = 0x40,
    BATTLE_REACTION_SET_2_MP_RESTORE = 0x20,
    BATTLE_REACTION_SET_2_CRITICAL_QUICK = 0x10,
    BATTLE_REACTION_SET_2_MEATBONE_SLASH = 0x08,
    BATTLE_REACTION_SET_2_COUNTER_MAGIC = 0x04,
    BATTLE_REACTION_SET_2_COUNTER_TACKLE = 0x02,
    BATTLE_REACTION_SET_2_COUNTER_FLOOD = 0x01,
} battle_unit_reaction_set_2_e;

typedef enum battle_unit_reaction_set_3 {
    BATTLE_REACTION_SET_3_ABSORB_USED_MP = 0x80,
    BATTLE_REACTION_SET_3_GILGAME_HEART = 0x40,
    BATTLE_REACTION_SET_3_REFLECT = 0x20,
    BATTLE_REACTION_SET_3_AUTO_POTION = 0x10,
    BATTLE_REACTION_SET_3_COUNTER = 0x08,
    /* 0x04 is present in the bitset but remains unidentified. */
    BATTLE_REACTION_SET_3_DISTRIBUTE = 0x02,
    BATTLE_REACTION_SET_3_MP_SWITCH = 0x01,
} battle_unit_reaction_set_3_e;

typedef enum battle_unit_reaction_set_4 {
    BATTLE_REACTION_SET_4_DAMAGE_SPLIT = 0x80,
    BATTLE_REACTION_SET_4_WEAPON_GUARD = 0x40,
    BATTLE_REACTION_SET_4_FINGER_GUARD = 0x20,
    BATTLE_REACTION_SET_4_ABANDON = 0x10,
    BATTLE_REACTION_SET_4_CATCH = 0x08,
    BATTLE_REACTION_SET_4_BLADE_GRASP = 0x04,
    BATTLE_REACTION_SET_4_ARROW_GUARD = 0x02,
    BATTLE_REACTION_SET_4_HAMEDO = 0x01,
} battle_unit_reaction_set_4_e;

typedef enum battle_movement_set_1 {
    BATTLE_MOVEMENT_SET_1_MOVE_PLUS_1 = 0x80,
    BATTLE_MOVEMENT_SET_1_MOVE_PLUS_2 = 0x40,
    BATTLE_MOVEMENT_SET_1_MOVE_PLUS_3 = 0x20,
    BATTLE_MOVEMENT_SET_1_JUMP_PLUS_1 = 0x10,
    BATTLE_MOVEMENT_SET_1_JUMP_PLUS_2 = 0x08,
    BATTLE_MOVEMENT_SET_1_JUMP_PLUS_3 = 0x04,
    BATTLE_MOVEMENT_SET_1_IGNORE_HEIGHT = 0x02,
    BATTLE_MOVEMENT_SET_1_MOVE_HP_UP = 0x01,
} battle_unit_movement_set_1_e;

typedef enum battle_movement_set_2 {
    BATTLE_MOVEMENT_SET_2_MOVE_MP_UP = 0x80,
    BATTLE_MOVEMENT_SET_2_MOVE_GET_EXP = 0x40,
    BATTLE_MOVEMENT_SET_2_MOVE_GET_JP = 0x20,
    BATTLE_MOVEMENT_SET_2_CANNOT_ENTER_WATER = 0x10,
    BATTLE_MOVEMENT_SET_2_TELEPORT = 0x08,
    BATTLE_MOVEMENT_SET_2_TELEPORT_2 = 0x04,
    BATTLE_MOVEMENT_SET_2_ANY_WEATHER = 0x02,
    BATTLE_MOVEMENT_SET_2_ANY_GROUND = 0x01,
} battle_unit_movement_set_2_e;

typedef enum battle_movement_set_3 {
    BATTLE_MOVEMENT_SET_3_WALK_ON_WATER = 0x80,
    BATTLE_MOVEMENT_SET_3_MOVE_IN_WATER = 0x40,
    BATTLE_MOVEMENT_SET_3_MOVE_ON_LAVA = 0x20,
    BATTLE_MOVEMENT_SET_3_MOVE_UNDERWATER = 0x10,
    BATTLE_MOVEMENT_SET_3_FLOAT = 0x08,
    BATTLE_MOVEMENT_SET_3_FLY = 0x04,
    BATTLE_MOVEMENT_SET_3_SILENT_WALK = 0x02,
    BATTLE_MOVEMENT_SET_3_MOVE_FIND_ITEM = 0x01,
} battle_unit_movement_set_3_e;

#endif
